import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedUserContext, createAdminClient } from "@/lib/supabase";
// @ts-expect-error – html-pdf-node has no official @types package
import htmlPdf from "html-pdf-node";

const BUCKET = "finance-exports";
const SIGNED_URL_TTL = 3600; // 1 hour

// ─── HTML template ────────────────────────────────────────────────────────────

function buildHtml(doc: Record<string, unknown>): string {
  const report = (doc.content_json as Record<string, unknown>)?.report ?? {};
  const r = report as Record<string, unknown>;
  const period = (doc.content_json as Record<string, unknown>)?.period as
    | { month?: string; year?: number }
    | undefined;

  const str = (v: unknown) =>
    typeof v === "string" ? v : typeof v === "number" ? String(v) : "—";
  const fmtNum = (v: unknown, prefix = "") =>
    typeof v === "number" ? `${prefix}${v.toLocaleString("en-IN")}` : str(v);
  const fmtPct = (v: unknown) => (typeof v === "number" ? `${v}%` : "—");
  const bullets = (v: unknown): string[] =>
    Array.isArray(v) ? v.map(String) : [];

  const kpis = [
    { label: "MRR", value: fmtNum(r.mrr, "₹") },
    { label: "ARR", value: fmtNum(r.arr, "₹") },
    { label: "MRR Growth", value: fmtPct(r.mrr_growth_percent) },
    { label: "Burn Rate", value: fmtNum(r.burn_rate, "₹") },
    { label: "Runway", value: `${str(r.runway_months)} months` },
    { label: "Gross Margin", value: fmtPct(r.gross_margin_percent) },
  ];

  const listItems = (arr: string[], color: string) =>
    arr
      .map(
        (item) =>
          `<li style="margin-bottom:6px;color:${color};"><span style="color:#374151">${item}</span></li>`,
      )
      .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Inter, Arial, sans-serif; background: #fff; color: #111827; font-size: 13px; line-height: 1.6; padding: 48px 56px; }
    .header { border-bottom: 3px solid #7C3AED; padding-bottom: 18px; margin-bottom: 28px; }
    .company { font-size: 22px; font-weight: 700; color: #111827; }
    .subtitle { font-size: 12px; color: #6B7280; margin-top: 4px; }
    .confidential { display: inline-block; margin-top: 6px; padding: 2px 9px; border: 1px solid #F59E0B; border-radius: 99px; font-size: 10px; color: #B45309; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; }
    .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.18em; color: #7C3AED; border-bottom: 1px solid #E5E7EB; padding-bottom: 5px; margin: 22px 0 10px; }
    .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 12px 0; }
    .kpi-card { background: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 6px; padding: 12px 14px; }
    .kpi-label { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.16em; color: #9CA3AF; margin-bottom: 4px; }
    .kpi-value { font-size: 20px; font-weight: 700; color: #111827; }
    p { color: #374151; font-size: 13px; line-height: 1.7; margin-bottom: 6px; }
    ul { padding-left: 0; list-style: none; }
    li { display: flex; align-items: flex-start; gap: 8px; margin-bottom: 6px; font-size: 13px; color: #374151; line-height: 1.55; }
    li::before { content: "›"; font-size: 17px; line-height: 1.2; flex-shrink: 0; }
    .footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #E5E7EB; font-size: 10px; color: #9CA3AF; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company">${String(doc.title ?? "Investor Report")}</div>
    <div class="subtitle">Period: ${period?.month ?? ""} ${period?.year ?? ""} &nbsp;·&nbsp; Prepared by AssembleOne Finance Agent</div>
    <span class="confidential">Confidential</span>
  </div>

  <div class="section-title">Executive Summary</div>
  <p>${str(r.executive_summary)}</p>

  <div class="section-title">Financial Snapshot</div>
  <div class="kpi-grid">
    ${kpis.map((k) => `<div class="kpi-card"><div class="kpi-label">${k.label}</div><div class="kpi-value">${k.value}</div></div>`).join("")}
  </div>

  <div class="section-title">Key Wins</div>
  <ul style="--bullet-color:#059669">${listItems(bullets(r.key_wins), "#059669")}</ul>

  <div class="section-title">Risks</div>
  <ul>${listItems(bullets(r.risks), "#DC2626")}</ul>

  <div class="section-title">Asks from Investors</div>
  <ul>${listItems(bullets(r.asks), "#7C3AED")}</ul>

  <div class="section-title">Next Month Targets</div>
  <ul>${listItems(bullets(r.next_month_targets), "#6B7280")}</ul>

  <div class="footer">Generated by AssembleOne Finance Agent &nbsp;·&nbsp; ${String(doc.title ?? "")} &nbsp;·&nbsp; Confidential</div>
</body>
</html>`;
}

// ─── Route ────────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest): Promise<NextResponse | Response> {
  try {
const auth = await getAuthenticatedUserContext();
if ("error" in auth) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }
const body = (await req.json()) as { documentId?: string; userId?: string };
const { documentId } = body;
if (!documentId) {
    return NextResponse.json({ error: "documentId is required." }, { status: 400 });
  }
const supabase = createAdminClient();
if (!supabase) {
    return NextResponse.json({ error: "Database not configured." }, { status: 503 });
  }
const { data: doc, error: fetchErr } = await supabase
    .from("finance_documents")
    .select("*")
    .eq("id", documentId)
    .eq("user_id", auth.userId)
    .single();
if (fetchErr || !doc) {
    return NextResponse.json({ error: "Document not found or access denied." }, { status: 404 });
  }
const html = buildHtml(doc as Record<string, unknown>);
const file = { content: html };
const options = {
    format: "A4",
    printBackground: true,
    margin: { top: "0mm", bottom: "0mm", left: "0mm", right: "0mm" },
  };
let pdfBuffer: Buffer;
try {
    pdfBuffer = await htmlPdf.generatePdf(file, options) as Buffer;
  } catch (e) {
    const msg = e instanceof Error ? e.message : "PDF generation failed.";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
const storagePath = `${auth.userId}/${documentId}/investor-report.pdf`;
const { error: uploadErr } = await supabase.storage
    .from(BUCKET)
    .upload(storagePath, pdfBuffer, {
      contentType: "application/pdf",
      upsert: true,
    });
if (uploadErr) {
    return NextResponse.json({ error: `Storage upload failed: ${uploadErr.message}` }, { status: 500 });
  }
await supabase
    .from("finance_documents")
    .update({ file_url: storagePath })
    .eq("id", documentId);
const { data: signedData, error: signErr } = await supabase.storage
    .from(BUCKET)
    .createSignedUrl(storagePath, SIGNED_URL_TTL);
if (signErr || !signedData) {
    return NextResponse.json({ error: "Could not create signed URL." }, { status: 500 });
  }
return NextResponse.json({ url: signedData.signedUrl, storagePath });
  } catch (error: any) {
    console.error("API error:", error);
    return NextResponse.json({ error: error.message || "Internal server error" }, { status: 500 });
  }
}
